// Generated by CoffeeScript 2.0.0-beta2
(function() {
  document.addEventListener('DOMContentLoaded', function() {
    window.browserPlus = {};
    browserPlus.menu = function(menu) {
      var submenu;
      if (!browserPlus.contextMenu) {
        browserPlus.contextMenu = jQuery("<ul id='bp-menu'></ul>");
        jQuery('body').append(browserPlus.contextMenu);
        browserPlus.contextMenu.hide();
        jQuery('body').on('contextmenu', function(e) {
          var maxHeight, maxWidth, positionX, positionY;
          if (!browserPlus.contextMenu.has('li').length) {
            return false;
          }
          browserPlus.contextMenu.css({
            top: 'auto',
            left: 'auto',
            bottom: 'auto',
            right: 'auto'
          });
          browserPlus.contextMenu.css({
            left: e.pageX,
            top: e.pageY
          });
          maxHeight = e.clientY + browserPlus.contextMenu.outerHeight();
          if (maxHeight > jQuery(window).height()) {
            positionY = e.pageY - browserPlus.contextMenu.outerHeight() - 10;
          } else {
            positionY = e.pageY + 10;
          }
          maxWidth = e.clientX + browserPlus.contextMenu.outerWidth();
          if (maxWidth > jQuery(window).width() + 10) {
            positionX = e.pageX - browserPlus.contextMenu.outerWidth() - 10;
          } else {
            positionX = e.pageX;
          }
          browserPlus.contextMenu.css({
            top: positionY,
            left: positionX
          });
          browserPlus.contextMenu.show();
          jQuery('body').one('click', function() {
            var children;
            browserPlus.contextMenu.hide();
            children = browserPlus.contextMenu.children('.bp-selector');
            children.off('click');
            return children.remove();
          });
          return false;
        });
      }
      if (menu.name) {
        if (menu.selector) {
          jQuery('body').on('contextmenu', menu.selector, function(e) {
            var submenu;
            if (jQuery('#bp-menu').is(':visible')) {
              return true;
            }
            if (browserPlus.contextMenu.children(`[data-bpid='${menu._id}']`).length) {
              return true;
            }
            if (menu.selectorFilter) {
              if (!eval(`(${menu.selectorFilter}).bind(this)()`)) {
                return true;
              }
            }
            submenu = jQuery(`<li class='bp-selector' data-bpid = '${menu._id}'> ${menu.name} </li>`);
            submenu.on('click', eval('(' + menu.fn + ').bind(this)'));
            return browserPlus.contextMenu.append(submenu);
          });
        } else {
          submenu = jQuery('<li>' + menu.name + '</li>');
          submenu.on('click', eval('(' + menu.fn + ').bind(this)'));
          browserPlus.contextMenu.append(submenu);
        }
      }
      if (menu.event) {
        if (menu.selector) {
          jQuery('body').on(menu.event, menu.selector, eval('(' + menu.fn + ')'));
        } else {
          jQuery('body').on(menu.event, eval('(' + menu.fn + ')'));
        }
      } else if (menu.ctrlkey) {
        menu.keytype = menu.keytype || 'keyup';
        jQuery('body').on(menu.keytype, menu.selector, menu.ctrlkey, eval('(' + menu.fn + ')'));
      }
    };
    if (typeof jQuery === 'undefined') {
      return console.log('~browser-plus-jquery~');
    } else {
      return console.log('~browser-plus-menu~');
    }
  });

}).call(this);
